server:
  port: ${port:5656}
spring:
  jpa:
    hibernate:
      ddl-auto: ${ddl.auto:update}
  datasource:
    url: ${datasource.url:jdbc:mysql://localhost:3306/file}
    username: ${datasource.username:root}
    password: ${datasource.password:root}
    driver-class-name: ${driver.class.name:com.mysql.jdbc.Driver}
